/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view.BanHang;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.table.DefaultTableModel;
import repository.PrintPDF;
import utility.DBConnect;

/**
 *
 * @author Admin
 */
public class FormHoaDonChiTiet extends javax.swing.JFrame {

    /**
     * Creates new form FormHoaDonChiTiet
     */
    DefaultTableModel model = new DefaultTableModel();
    int index;
    int maHoaDon;

    public FormHoaDonChiTiet(int maHoaDon) {
        initComponents();
        setLocationRelativeTo(null);
        loadInvoiceDetails(maHoaDon);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jplHoaDon = new javax.swing.JPanel();
        lblThuNgan = new javax.swing.JLabel();
        lblBan = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        lblNgayIn = new javax.swing.JLabel();
        lblTongTien1 = new javax.swing.JLabel();
        lblKhachHang = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        lblMaHoaDon = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblPTTT = new javax.swing.JLabel();
        lblTongTien = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblHoaDon = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblThuNgan.setText("Người thu ngân");

        lblBan.setText("Số bàn");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon.two/logout-line-icon (2).png"))); // NOI18N
        jButton1.setText("Thoát");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        lblNgayIn.setText("Ngày in hóa đơn");

        lblTongTien1.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        lblTongTien1.setText("Tổng tiền");

        lblKhachHang.setText("Tên khách hàng");

        jLabel17.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel17.setText("Cảm ơn quý khách - Hẹn gặp lại <333");

        lblMaHoaDon.setText("Mã hóa đơn");

        jLabel6.setText("Khách hàng:");

        lblPTTT.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        lblPTTT.setText("PTTT");

        lblTongTien.setText("Tổng tiền");

        jLabel5.setText("Thu ngân:");

        jLabel4.setText("Bàn:");

        jLabel3.setText("Ngày:");

        jLabel12.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        jLabel12.setText("Tổng cộng");

        jLabel2.setText("Số HĐ:");

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon.two/food-icon.png"))); // NOI18N
        jLabel1.setText("Hóa đơn thanh toán");

        tblHoaDon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tên món", "SL", "Đơn giá", "Thành tiền"
            }
        ));
        jScrollPane1.setViewportView(tblHoaDon);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon.two/printPDF.png"))); // NOI18N
        jButton2.setText("In hóa đơn");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jplHoaDonLayout = new javax.swing.GroupLayout(jplHoaDon);
        jplHoaDon.setLayout(jplHoaDonLayout);
        jplHoaDonLayout.setHorizontalGroup(
            jplHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jplHoaDonLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(76, 76, 76))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jplHoaDonLayout.createSequentialGroup()
                .addGap(0, 12, Short.MAX_VALUE)
                .addGroup(jplHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jplHoaDonLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(jplHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addGroup(jplHoaDonLayout.createSequentialGroup()
                                .addComponent(lblPTTT, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblTongTien1)))
                        .addGap(158, 158, 158))
                    .addGroup(jplHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jplHoaDonLayout.createSequentialGroup()
                            .addGap(134, 134, 134)
                            .addComponent(lblTongTien, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jplHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jplHoaDonLayout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addGroup(jplHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jplHoaDonLayout.createSequentialGroup()
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblBan, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jplHoaDonLayout.createSequentialGroup()
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblNgayIn, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jplHoaDonLayout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jplHoaDonLayout.createSequentialGroup()
                                        .addGroup(jplHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel5))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jplHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblThuNgan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblMaHoaDon, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
            .addGroup(jplHoaDonLayout.createSequentialGroup()
                .addGroup(jplHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jplHoaDonLayout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addComponent(jLabel1))
                    .addGroup(jplHoaDonLayout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(jLabel17)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jplHoaDonLayout.setVerticalGroup(
            jplHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jplHoaDonLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(37, 37, 37)
                .addGroup(jplHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lblMaHoaDon))
                .addGap(20, 20, 20)
                .addGroup(jplHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lblNgayIn))
                .addGap(18, 18, 18)
                .addGroup(jplHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(lblBan))
                .addGap(18, 18, 18)
                .addGroup(jplHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(lblThuNgan))
                .addGap(18, 18, 18)
                .addGroup(jplHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(lblKhachHang))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jplHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jplHoaDonLayout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(43, 43, 43)
                        .addGroup(jplHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTongTien1)
                            .addComponent(lblPTTT)))
                    .addComponent(lblTongTien))
                .addGap(52, 52, 52)
                .addGroup(jplHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton1))
                .addGap(35, 35, 35)
                .addComponent(jLabel17)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jplHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jplHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        dispose();

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:

        //        FormHoaDon fh = new FormHoaDon(maHoaDon);
        PrintPDF pdf = new PrintPDF();
        pdf.exportJFrameToPDF(jplHoaDon, "D:/DuAn1/Vinh_ProJect/HoaDon/" + "HoaDon" + "" + lblMaHoaDon.getText() + ".pdf");
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormHoaDonChiTiet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormHoaDonChiTiet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormHoaDonChiTiet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormHoaDonChiTiet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormHoaDonChiTiet(ABORT).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel jplHoaDon;
    private javax.swing.JLabel lblBan;
    private javax.swing.JLabel lblKhachHang;
    private javax.swing.JLabel lblMaHoaDon;
    private javax.swing.JLabel lblNgayIn;
    private javax.swing.JLabel lblPTTT;
    private javax.swing.JLabel lblThuNgan;
    private javax.swing.JLabel lblTongTien;
    private javax.swing.JLabel lblTongTien1;
    private javax.swing.JTable tblHoaDon;
    // End of variables declaration//GEN-END:variables
private void loadInvoiceDetails(int maHoaDon) {
        Connection conn = null;
        try {
            conn = DBConnect.getConnection();

            // Truy vấn thông tin hóa đơn và lấy MaDonHang
            String queryHoaDon = "SELECT dh.MaDonHang, dh.MaBan, dh.TenKhachHang, dh.NgayGioDat, hd.TongTien AS HoaDonTongTien, "
                    + "hd.MaHoaDon, hd.MaNhanVien, hd.NgayLap, hd.PhuongThucThanhToan "
                    + "FROM HoaDon hd "
                    + "INNER JOIN DonHang dh ON hd.MaDonHang = dh.MaDonHang "
                    + "WHERE hd.MaHoaDon = ?";
            PreparedStatement stmtHoaDon = conn.prepareStatement(queryHoaDon);
            stmtHoaDon.setInt(1, maHoaDon);
            ResultSet rsHoaDon = stmtHoaDon.executeQuery();

            int maDonHang = -1;
            if (rsHoaDon.next()) {
                // Lưu lại MaDonHang
                maDonHang = rsHoaDon.getInt("MaDonHang");

                // Hiển thị thông tin hóa đơn trong form
                lblMaHoaDon.setText("HD" + String.valueOf(rsHoaDon.getInt("MaHoaDon")));
                lblKhachHang.setText(rsHoaDon.getString("TenKhachHang"));
                lblBan.setText(String.valueOf(rsHoaDon.getInt("MaBan")));
                lblNgayIn.setText(rsHoaDon.getString("NgayGioDat"));
                lblTongTien.setText(String.valueOf(rsHoaDon.getDouble("HoaDonTongTien")));
                lblTongTien1.setText(String.valueOf(rsHoaDon.getDouble("HoaDonTongTien")));
                lblNgayIn.setText(rsHoaDon.getString("NgayLap"));
                lblPTTT.setText(rsHoaDon.getString("PhuongThucThanhToan"));
                lblThuNgan.setText("Nhân viên " + String.valueOf(rsHoaDon.getInt("MaNhanVien")));
            }

            // Nếu không tìm thấy MaDonHang, thoát khỏi phương thức
            if (maDonHang == -1) {
                System.out.println("Không tìm thấy MaDonHang cho MaHoaDon: " + maHoaDon);
                return;
            }

            // Truy vấn chi tiết sản phẩm dựa trên MaDonHang
            String queryDetails = "SELECT sp.TenSanPham, hdc.SoLuong, sp.DonGia, (hdc.SoLuong * sp.DonGia) AS ThanhTien "
                    + "FROM HoaDonChiTiet hdc "
                    + "INNER JOIN SanPham sp ON hdc.MaSanPham = sp.MaSanPham "
                    + "WHERE hdc.MaHoaDon = ?";
            PreparedStatement stmtDetails = conn.prepareStatement(queryDetails);
            stmtDetails.setInt(1, maHoaDon);
            ResultSet rsDetails = stmtDetails.executeQuery();

            // Hiển thị chi tiết sản phẩm vào bảng trong form
            DefaultTableModel model = (DefaultTableModel) tblHoaDon.getModel();
            model.setRowCount(0);  // Xóa dữ liệu cũ
            while (rsDetails.next()) {
                model.addRow(new Object[]{
                    rsDetails.getString("TenSanPham"),
                    rsDetails.getInt("SoLuong"),
                    rsDetails.getDouble("DonGia"),
                    rsDetails.getDouble("ThanhTien")
                });
            }

        } catch (Exception e) {
            e.printStackTrace();
        } finally {
            if (conn != null) {
                try {
                    conn.close();  // Đóng kết nối
                } catch (Exception e) {
                    e.printStackTrace();
                }
            }
        }
    }
}
