/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view.ThongKe;

import java.util.Map;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.renderer.category.BarRenderer;
import org.jfree.data.category.DefaultCategoryDataset;
import repository.HoaDonRepo;

/**
 *
 * @author Admin
 */
public class BieuDoSoHoaDon extends javax.swing.JFrame {

    /**
     * Creates new form ChartHoaDonByThang
     */
    public BieuDoSoHoaDon() {
        initComponents();
        setLocationRelativeTo(null);
        showBarChart();
    }

    public void showBarChart() {
        HoaDonRepo repository = new HoaDonRepo();
        Map<String, Integer> hoaDonData = repository.getSoHoaDonTheoThang();

        // Tạo dataset cho biểu đồ
        DefaultCategoryDataset dataset = new DefaultCategoryDataset();
        for (Map.Entry<String, Integer> entry : hoaDonData.entrySet()) {
            dataset.addValue(entry.getValue(), "Số hóa đơn", entry.getKey());
        }

        // Tạo biểu đồ cột (Bar Chart)
        JFreeChart barChart = ChartFactory.createBarChart(
                "Biểu đồ số hóa đơn theo tháng", // Tiêu đề
                "Tháng", // Trục X
                "Số hóa đơn", // Trục Y
                dataset // Dataset
        );

        // Tùy chỉnh màu sắc của các thanh
        CategoryPlot plot = barChart.getCategoryPlot();
        BarRenderer renderer = (BarRenderer) plot.getRenderer();
        renderer.setSeriesPaint(0, new java.awt.Color(0, 102, 204)); // Màu xanh dương cho thanh

        // Thêm hiệu ứng shadow cho các thanh
        renderer.setShadowVisible(true);
        renderer.setShadowXOffset(2);
        renderer.setShadowYOffset(2);

        // Tùy chỉnh tiêu đề biểu đồ
        barChart.setTitle("Biểu đồ số hóa đơn theo tháng");
        barChart.getTitle().setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 16)); // Thay đổi phông chữ và kích thước tiêu đề

        // Tùy chỉnh trục X và Y
        plot.getDomainAxis().setLabelFont(new java.awt.Font("Arial", java.awt.Font.PLAIN, 12)); // Font của trục X
        plot.getRangeAxis().setLabelFont(new java.awt.Font("Arial", java.awt.Font.PLAIN, 12));  // Font của trục Y
        plot.getDomainAxis().setTickLabelFont(new java.awt.Font("Arial", java.awt.Font.PLAIN, 10)); // Font của các nhãn trên trục X
        plot.getRangeAxis().setTickLabelFont(new java.awt.Font("Arial", java.awt.Font.PLAIN, 10));  // Font của các nhãn trên trục Y

        // Thêm biểu đồ vào ChartPanel
        ChartPanel chartPanel = new ChartPanel(barChart);
        chartPanel.setPreferredSize(new java.awt.Dimension(800, 600)); // Kích thước biểu đồ

        // Thêm ChartPanel vào JPanel chartPanel
        this.chartPanel.setLayout(new java.awt.BorderLayout());
        this.chartPanel.add(chartPanel, java.awt.BorderLayout.CENTER);
        this.chartPanel.validate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        chartPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1009, 584));

        chartPanel.setPreferredSize(new java.awt.Dimension(1009, 584));

        javax.swing.GroupLayout chartPanelLayout = new javax.swing.GroupLayout(chartPanel);
        chartPanel.setLayout(chartPanelLayout);
        chartPanelLayout.setHorizontalGroup(
            chartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 939, Short.MAX_VALUE)
        );
        chartPanelLayout.setVerticalGroup(
            chartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 561, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(chartPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 939, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(chartPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 561, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BieuDoSoHoaDon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BieuDoSoHoaDon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BieuDoSoHoaDon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BieuDoSoHoaDon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BieuDoSoHoaDon().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel chartPanel;
    // End of variables declaration//GEN-END:variables
}
