/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view.ThongKe;

import com.toedter.calendar.JCalendar;
import java.io.File;
import java.io.FileOutputStream;
import java.math.BigDecimal;
import repository.HienThiDuLieuThongKe;
import utility.DBConnect;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import javax.swing.Icon;
import javax.swing.JDialog;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;
import model.HoaDon;
import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.ss.usermodel.Workbook;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;
import repository.HoaDonRepo;
import view.TrangChu.*;
import view.BanHang.FormDonHang;
import view.BanHang.FormHoaDon;
import view.BanHang.FormHoaDonChiTiet;
import view.BanHang.FormOrder;
import view.QuanLyNhanVien.FormQuanLyNhanVien;
import view.SanPham.FormQuanLySanPham;
import view.ThongKe.FormThongKe;
import view.ban.FormDatBan;

/**
 *
 * @author Admin
 */
public class FormThongKe extends javax.swing.JFrame {

    /**
     * Creates new form FormTrangChu
     */
    HoaDonRepo rp = new HoaDonRepo();
    DefaultTableModel model = new DefaultTableModel();

    public FormThongKe() {
        initComponents();
        setLocationRelativeTo(null);
        model = (DefaultTableModel) tblHoaDon.getModel();
        fillToTable();
        HienThiDuLieuThongKe httk = new HienThiDuLieuThongKe(lblSoHoaDon);
        HienThiDuLieuThongKe httk2 = new HienThiDuLieuThongKe(lblTongThuNhap);
        httk.tongHoaDon();
        httk2.tongTien();
        hienThiTenSanPham();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblTongThuNhap = new javax.swing.JLabel();
        lblSoHoaDon = new javax.swing.JLabel();
        lblBestMon = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        txtMaHoaDon = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel31 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jCalendar = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblHoaDon = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        lblRole = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon.two/food50px.png"))); // NOI18N
        jLabel2.setText("Three restaurant");

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon.two/buyer-pay-icon.png"))); // NOI18N
        jLabel3.setText("Tổng thu nhập");

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon.two/hoadon.png"))); // NOI18N
        jLabel4.setText("Số hóa đơn");

        lblTongThuNhap.setForeground(new java.awt.Color(0, 0, 0));
        lblTongThuNhap.setText("jLabel5");

        lblSoHoaDon.setForeground(new java.awt.Color(0, 0, 0));
        lblSoHoaDon.setText("jLabel5");

        lblBestMon.setForeground(new java.awt.Color(0, 0, 0));
        lblBestMon.setText("jLabel5");

        jLabel8.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon.two/food-icon.png"))); // NOI18N
        jLabel8.setText("Món được chọn nhiều nhất");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(55, 55, 55)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(lblBestMon, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(lblTongThuNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(lblSoHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(172, 172, 172))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTongThuNhap)
                            .addComponent(lblSoHoaDon)))
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addComponent(jLabel8)
                            .addGap(18, 18, 18)
                            .addComponent(lblBestMon))
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon.two/search-line-icon.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel31.setForeground(new java.awt.Color(0, 0, 0));
        jLabel31.setText("Mã hóa đơn");

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon.two/invoice-receipt-icon.png"))); // NOI18N
        jButton3.setText("Xuất danh sách hóa đơn");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/account_24px.png"))); // NOI18N
        jButton4.setText("Biểu đồ");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jCalendar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCalendarMouseClicked(evt);
            }
        });

        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Tìm kiếm theo ngày, tháng, năm");

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon.two/search-line-icon.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jCalendar, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel31)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jButton4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(txtMaHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        jPanel5Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButton3, txtMaHoaDon});

        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(10, 10, 10)
                        .addComponent(jCalendar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addComponent(jLabel31)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMaHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addComponent(jButton3)
                .addGap(18, 18, 18)
                .addComponent(jButton4)
                .addContainerGap(211, Short.MAX_VALUE))
        );

        jPanel5Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jButton3, txtMaHoaDon});

        tblHoaDon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã hóa đơn", "Mã đơn hàng", "Nhân viên", "Ngày lập", "Tổng tiền", "Phương thức thanh toán"
            }
        ));
        tblHoaDon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblHoaDonMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblHoaDon);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(0, 69, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 962, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(74, 74, 74))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 432, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(62, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 1440, 620));

        jPanel6.setBackground(new java.awt.Color(255, 153, 51));

        jLabel33.setFont(new java.awt.Font("Dialog", 3, 35)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(255, 255, 255));
        jLabel33.setText("Three Restaurant FPOLY");

        jLabel34.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon.two/home50px.png"))); // NOI18N
        jLabel34.setText("jLabel4");
        jLabel34.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel34MouseClicked(evt);
            }
        });

        lblRole.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lblRole.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/male_user_50px.png"))); // NOI18N
        lblRole.setText("admin");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 421, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 814, Short.MAX_VALUE)
                .addComponent(lblRole)
                .addGap(27, 27, 27))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap(50, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel33, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(lblRole)
                        .addGap(9, 9, 9)))
                .addGap(21, 21, 21))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel34)
                .addGap(34, 34, 34))
        );

        getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1440, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser("D:\\anh");
        fileChooser.setDialogTitle("Lưu file Excel");
        fileChooser.setFileFilter(new javax.swing.filechooser.FileNameExtensionFilter("Excel Files", "xlsx"));
        int userSelection = fileChooser.showSaveDialog(this);

        if (userSelection == JFileChooser.APPROVE_OPTION) {
            File fileToSave = fileChooser.getSelectedFile();
            if (!fileToSave.getAbsolutePath().endsWith(".xlsx")) {
                fileToSave = new File(fileToSave.getAbsolutePath() + ".xlsx");
            }
            try ( Workbook workbook = new XSSFWorkbook()) {
                org.apache.poi.ss.usermodel.Sheet sheet = workbook.createSheet("Sản Phẩm");
                Row headerRow = sheet.createRow(0);
                headerRow.createCell(0).setCellValue("Mã hóa đơn");
                headerRow.createCell(1).setCellValue("Mã đơn hàng");
                headerRow.createCell(2).setCellValue("Nhân viên");
                headerRow.createCell(3).setCellValue("Ngày lập");
                headerRow.createCell(4).setCellValue("Tổng tiền");
                headerRow.createCell(5).setCellValue("Phương thức thanh toán");
                for (int i = 0; i < model.getRowCount(); i++) {
                    Row row = sheet.createRow(i + 1);
                    for (int j = 0; j < model.getColumnCount(); j++) {
                        Object cellValue = model.getValueAt(i, j);
                        row.createCell(j).setCellValue(cellValue != null ? cellValue.toString() : "");
                    }
                }
                try ( FileOutputStream outputStream = new FileOutputStream(fileToSave)) {
                    workbook.write(outputStream);
                    JOptionPane.showMessageDialog(this, "Xuất Excel thành công!");
                }
            } catch (Exception e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(this, "Lỗi: " + e.getMessage());
            }
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void tblHoaDonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblHoaDonMouseClicked
        // TODO add your handling code here:
        int row = tblHoaDon.rowAtPoint(evt.getPoint());
        int column = tblHoaDon.columnAtPoint(evt.getPoint());

        if (row >= 0) {
            // Lấy Mã Hóa Đơn (giả sử cột đầu tiên chứa Mã Hóa Đơn)
            int maHoaDon = (int) tblHoaDon.getValueAt(row, 0);  // Giả sử cột đầu tiên chứa Mã Hóa Đơn

            // Truyền MaHoaDon vào form chi tiết hóa đơn
            FormHoaDonChiTiet hoaDonChiTietForm = new FormHoaDonChiTiet(maHoaDon);
            hoaDonChiTietForm.setVisible(true);  // Hiển thị form chi tiết hóa đơn
        }

    }//GEN-LAST:event_tblHoaDonMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String maHoaDon = txtMaHoaDon.getText();
        searchHoaDonByMaHoaDon(maHoaDon);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jCalendarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCalendarMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_jCalendarMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Date selectedDate = jCalendar.getDate();

        // Kiểm tra xem có ngày nào được chọn không
        if (selectedDate != null) {
            // Tiến hành tìm kiếm theo ngày đã chọn
            searchByDate(selectedDate);
        } else {
            // Nếu không có ngày được chọn, hiển thị thông báo lỗi
            JOptionPane.showMessageDialog(null, "Vui lòng chọn một ngày để tìm kiếm.");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        String[] options = {"Doanh Thu", "Số Hóa Đơn", "Tăng Trưởng"};

// Tạo một Icon cho hộp thoại thông báo (có thể thay đổi icon tùy thích)
        Icon icon = UIManager.getIcon("OptionPane.informationIcon");

// Hiển thị hộp thoại với các tùy chọn
        int choice = JOptionPane.showOptionDialog(this,
                "<html><div align='center'><h3><font color='black'>Chọn biểu đồ thống kê</font></h3></div></html>", // Nội dung thông báo với HTML và căn giữa
                "Thống Kê", // Tiêu đề hộp thoại
                JOptionPane.DEFAULT_OPTION,
                JOptionPane.INFORMATION_MESSAGE, // Chọn loại thông báo (Icon thông báo)
                icon, // Biểu tượng của hộp thoại
                options, // Các lựa chọn
                options[0]); // Lựa chọn mặc định

// Xử lý theo lựa chọn
        if (choice == 0) {
            // Mở form biểu đồ Doanh Thu
            openFormDoanhThu();
        } else if (choice == 1) {
            // Mở form biểu đồ Số Hóa Đơn
            openFormSoHoaDon();
        } else if (choice == 2) {
            // Mở form biểu đồ Tốc Độ Tăng Trưởng
            openFormTangTruong();
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jLabel34MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel34MouseClicked
        // TODO add your handling code here:
        FormTrangChu ct = new FormTrangChu();
        ct.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel34MouseClicked

// Mở form Số Hóa Đơn
    private void openFormDoanhThu() {
        // Tạo form Doanh Thu
        BieuDoDoanhThu formDoanhThu = new BieuDoDoanhThu();
        formDoanhThu.setDefaultCloseOperation(JDialog.DISPOSE_ON_CLOSE);  // Đảm bảo form này đóng khi không còn cần thiết
        formDoanhThu.setSize(800, 600);  // Đặt kích thước cho form
        formDoanhThu.setLocationRelativeTo(null);  // Đưa cửa sổ về giữa màn hình
        formDoanhThu.setVisible(true);  // Mở form Doanh Thu
    }

    private void openFormSoHoaDon() {
        // Tạo form Số Hóa Đơn
        BieuDoSoHoaDon formSoHoaDon = new BieuDoSoHoaDon();
        formSoHoaDon.setDefaultCloseOperation(JDialog.DISPOSE_ON_CLOSE);  // Đảm bảo form này đóng khi không còn cần thiết
        formSoHoaDon.setSize(800, 600);  // Đặt kích thước cho form
        formSoHoaDon.setLocationRelativeTo(null);  // Đưa cửa sổ về giữa màn hình
        formSoHoaDon.setVisible(true);  // Mở form Số Hóa Đơn
    }

    private void openFormTangTruong() {
        // Tạo form Tốc Độ Tăng Trưởng
        BieuDoTangTruong formTangTruong = new BieuDoTangTruong();
        formTangTruong.setDefaultCloseOperation(JDialog.DISPOSE_ON_CLOSE);  // Đảm bảo form này đóng khi không còn cần thiết
        formTangTruong.setSize(800, 600);  // Đặt kích thước cho form
        formTangTruong.setLocationRelativeTo(null);  // Đưa cửa sổ về giữa màn hình
        formTangTruong.setVisible(true);  // Mở form Tốc Độ Tăng Trưởng
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormThongKe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormThongKe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormThongKe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormThongKe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormThongKe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private com.toedter.calendar.JDateChooser jCalendar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBestMon;
    private javax.swing.JLabel lblRole;
    private javax.swing.JLabel lblSoHoaDon;
    private javax.swing.JLabel lblTongThuNhap;
    private javax.swing.JTable tblHoaDon;
    private javax.swing.JTextField txtMaHoaDon;
    // End of variables declaration//GEN-END:variables
    private void fillToTable() {

        ArrayList<HoaDon> list = rp.getAll();

        model.setRowCount(0);

        for (HoaDon hd : list) {
            model.addRow(new Object[]{
                hd.getMaHoaDon(), hd.getMaDonHang(), hd.getMaNhanVien(),
                hd.getNgayLap(), hd.getTongTien(), hd.getPhuongThucThanhToan()
            });
        }
    }

    private void hienThiTenSanPham() {
        // Giả sử bạn đã có kết nối cơ sở dữ liệu và câu lệnh SQL
        String query = "SELECT top 1 sp.TenSanPham, SUM(hdct.SoLuong) AS TongSoLuong\n"
                + "FROM HoaDonChiTiet hdct\n"
                + "JOIN SanPham sp ON hdct.MaSanPham = sp.MaSanPham\n"
                + "GROUP BY sp.TenSanPham\n"
                + "ORDER BY TongSoLuong DESC;"; // Lấy sản phẩm bán nhiều nhất

        try ( Connection con = DBConnect.getConnection();  PreparedStatement pst = con.prepareStatement(query);  ResultSet rs = pst.executeQuery()) {

            if (rs.next()) {
                // Lấy tên sản phẩm từ ResultSet
                String tenSanPham = rs.getString("TenSanPham");

                // Cập nhật tên sản phẩm lên JLabel
                lblBestMon.setText("" + tenSanPham);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void searchHoaDonByMaHoaDon(String maHoaDon) {
        // Tìm kiếm theo mã hóa đơn
        List<HoaDon> hoaDonList = rp.searchByMaHoaDon(maHoaDon);

        // Định nghĩa các cột của JTable
        String[] columns = {"Mã Hóa Đơn", "Mã Đơn Hàng", "Mã Nhân Viên", "Ngày Lập", "Tổng Tiền", "Phương Thức Thanh Toán"};

        // Tạo model cho JTable
        DefaultTableModel model = new DefaultTableModel(columns, 0);

        // Duyệt qua danh sách và thêm các dòng vào model
        for (HoaDon hoaDon : hoaDonList) {
            Object[] row = {
                hoaDon.getMaHoaDon(),
                hoaDon.getMaDonHang(),
                hoaDon.getMaNhanVien(),
                hoaDon.getNgayLap(),
                hoaDon.getTongTien(),
                hoaDon.getPhuongThucThanhToan()
            };
            model.addRow(row);
        }

        // Gán model vào JTable
        tblHoaDon.setModel(model);
    }

    private void searchByDate(Date selectedDate) {
        // Gọi phương thức trong Repository để lấy dữ liệu hóa đơn theo ngày
        ArrayList<HoaDon> hoaDonList = rp.getHoaDonByDate(selectedDate);

        // Cập nhật JTable với dữ liệu mới
        DefaultTableModel model = (DefaultTableModel) tblHoaDon.getModel();
        model.setRowCount(0); // Xóa hết dữ liệu cũ trong bảng

        // Thêm từng dòng dữ liệu vào bảng
        for (HoaDon hoaDon : hoaDonList) {
            Object[] row = {
                hoaDon.getMaHoaDon(),
                hoaDon.getMaDonHang(),
                hoaDon.getMaNhanVien(),
                hoaDon.getNgayLap(),
                hoaDon.getTongTien(),
                hoaDon.getPhuongThucThanhToan()
            };
            model.addRow(row); // Thêm dữ liệu vào bảng
        }
    }

}
